/**
 * Represents a paginated response from the API, providing a slice of data and metadata about the pagination state.
 * @template T The type of the content in the page.
 */
export interface Page<T> {
  /** The array of items for the current page. */
  content: T[]

  /** An object containing detailed information about the pagination and sorting. */
  pageable: {
    sort: {
      sorted: boolean
      unsorted: boolean
      empty: boolean
    }
    offset: number
    pageNumber: number
    pageSize: number
    paged: boolean
    unpaged: boolean
  }

  /** The total number of pages available. */
  totalPages: number

  /** The total number of elements across all pages. */
  totalElements: number

  /** A boolean indicating if this is the last page. */
  last: boolean

  /** The number of elements requested for this page. */
  size: number

  /** The current page number (0-indexed). */
  number: number

  /** An object describing the sorting applied to the query. */
  sort: {
    sorted: boolean
    unsorted: boolean
    empty: boolean
  }

  /** The number of elements on the current page. */
  numberOfElements: number

  /** A boolean indicating if this is the first page. */
  first: boolean

  /** A boolean indicating if the content for this page is empty. */
  empty: boolean
}

/**
 * Represents general statistics about the platform's state.
 */
export interface PlatformStats {
  /** A unique identifier for the stats record (if stored). */
  id: number

  /** The total number of projects on the platform. */
  projectCount: number

  /** The total number of registered users. */
  userCount: number

  /** The total number of files stored. */
  fileCount: number

  /** The total disk space currently used by files, typically in bytes. */
  spaceOnDisk: number

  /** The maximum available disk space for storage, typically in bytes. */
  maxSpaceOnDisk: number

  /** The timestamp of the platform stats*/
  createdAt: string
}

/**
 * Represents the request payload for creating a new user invitation.
 */
export interface UserCreationRequest {
  /** The email address of the user to be invited. */
  email: string

  /** The role to be assigned to the user upon registration. */
  role: 'USER' | 'EDITOR' | 'ADMIN'

  /** An array of project IDs to pre-associate with the user upon registration. */
  projectIds: string[]
}

/**
 * Represents the request payload for completing the user registration
 */
export interface CompleteRegistrationRequest {
  /** The invited user name*/
  name: string

  /** The invited user last name*/
  lastName: string

  /** The invited user username*/
  username: string

  /** The invited user password, it must be at least 8 characters*/
  password: string
}

/**
 * Represents the API response for a user invitation.
 */
export interface InvitationResponse {
  /** The invited user's email. */
  email: string

  /** The unique registration link generated by the server for the user to complete their signup. */
  registrationLink: string

  /** The current status of the invitation. */
  status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED'
}

/**
 * Represents the public-facing information of a registered user.
 * This is used for API responses and should not contain sensitive data like passwords.
 */
export interface UserResponse {
  /** The unique identifier for the user. */
  id: string

  /** The user's unique username. */
  username: string

  /** The user's first name. */
  name: string

  /** The user's last name. */
  lastName: string

  /** The user's email address. */
  email: string

  /** The role assigned to the user, which determines their permissions. */
  role: 'USER' | 'EDITOR' | 'ADMIN'
}

/**
 * Represents the request payload for updating an existing user's information.
 */
export interface UpdateUserRequest {
  /** The user's updated username. */
  username: string

  /** The user's updated first name. */
  name: string

  /** The user's updated last name. */
  lastName: string

  /** The user's updated email address. */
  email: string

  /** The user's updated role. */
  userType: 'USER' | 'EDITOR' | 'ADMIN'
}

/**
 * Represents the payload for updating an existing project's details.
 *
 * All fields are optional to allow for partial updates (e.g., changing only the description).
 */
export interface UpdateProjectRequest {
  /** The unique numeric identifier for the project. */
  id?: string

  /** The name of the project. */
  name?: string

  /** A brief description of the project. */
  description?: string

  /** List of user IDs to be modified in the project*/
  userIds?: string[]
}

/**
 * Represents a request to start the password recovery process.
 *
 * This is typically sent when a user provides their email to receive
 * a password reset link.
 */
export interface PasswordRecoveryRequest {
  /** The email address associated with the user account. */
  email: string
}

/**
 * Represents a request to reset the user's password.
 *
 * This is sent after the user clicks the recovery link and provides
 * a new password.
 */
export interface PasswordResetRequest {
  /** The unique recovery token sent to the user's email. */
  token: string

  /** The new password to set for the user account. */
  password: string
}

/**
 * Represents a response returned by the password recovery endpoints.
 *
 * It provides feedback about the request status, along with optional
 * metadata or messages to display to the user.
 */
export interface PasswordRecoveryResponse {
  /** Optional email (useful for confirmation responses). */
  email: string

  /** A token to the recovery link. */
  token: string

  /** Optional timestamp for when the action occurred. */
  timestamp?: string

  /** Whether the operation was successful (e.g., link sent, password reset). */
  status: 'PENDING' | 'USED' | 'EXPIRED' | 'REVOKED'
}

/**
 * Represents the file metadata returned by the file management endpoints.
 *
 * This object contains all necessary details to identify, display,
 * and download a specific file associated with a project.
 */
export interface FileResponse {
  /** The unique identifier (UUID) for the file. */
  uniqueId: string

  /** The name of the file (e.g., 'report.pdf', 'main.java'). */
  fileName: string

  /** The classification or extension type of the file. */
  fileType: string

  /** The size of the file in bytes. */
  fileSize: number

  /** The fully qualified URL to download or access the file. */
  downloadUrl: string

  /** The timestamp when the file was uploaded or created (ISO 8601 format). */
  createdAt: string
}

/**
 * Represents a response returned by the password recovery validation endpoint
 *
 * It provides information about the validity of a request, along with its
 * associated details.
 * */
export interface TokenValidationResponse {
  valid: boolean
  recovery: PasswordRecoveryRequest
}

/**
 * Represents the payload required to initiate the creation of a new project.
 *
 * This object aggregates the core project details and the initial list
 * of users to be associated with the project.
 */
export interface CreateProjectRequest {
  /** The display name of the project. */
  name: string

  /** A detailed description of the project's purpose and goals. */
  description: string

  /** A list of unique user identifiers (UUIDs) to be assigned as members of the project. */
  userIds: string[]
}

/**
 * Represents the subset of project data returned after creation or update operations.
 *
 * This response provides the immediate confirmation details of the project
 * stored in the system.
 */
export interface ProjectResponse {
  /** The unique identifier (UUID) assigned to the project. */
  id: string

  /** The name of the project. */
  name: string

  /** The description of the project. */
  description: string

  /** The current list of users present in the project*/
  userIds: string[]

  /** The timestamp when the project was created (ISO 8601 format). */
  createdAt: string

  /** The timestamp when the project was last modified (ISO 8601 format). */
  updatedAt: string
}
