/**
 * Represents a paginated response from the API, providing a slice of data and metadata about the pagination state.
 * @template T The type of the content in the page.
 */
export interface Page<T> {
  /** The array of items for the current page. */
  content: T[];

  /** An object containing detailed information about the pagination and sorting. */
  pageable: {
    sort: {
      sorted: boolean;
      unsorted: boolean;
      empty: boolean;
    };
    offset: number;
    pageNumber: number;
    pageSize: number;
    paged: boolean;
    unpaged: boolean;
  };

  /** The total number of pages available. */
  totalPages: number;

  /** The total number of elements across all pages. */
  totalElements: number;

  /** A boolean indicating if this is the last page. */
  last: boolean;

  /** The number of elements requested for this page. */
  size: number;

  /** The current page number (0-indexed). */
  number: number;

  /** An object describing the sorting applied to the query. */
  sort: {
    sorted: boolean;
    unsorted: boolean;
    empty: boolean;
  };

  /** The number of elements on the current page. */
  numberOfElements: number;

  /** A boolean indicating if this is the first page. */
  first: boolean;

  /** A boolean indicating if the content for this page is empty. */
  empty: boolean;
}

/**
 * Represents general statistics about the platform's state.
 */
export interface PlatformStats {
  /** A unique identifier for the stats record (if stored). */
  id: number;

  /** The total number of projects on the platform. */
  projectCount: number;

  /** The total number of registered users. */
  userCount: number;

  /** The total number of files stored. */
  fileCount: number;

  /** The total disk space currently used by files, typically in bytes. */
  spaceOnDisk: number;

  /** The maximum available disk space for storage, typically in bytes. */
  maxSpaceOnDisk: number;
}

/**
 * Represents the request payload for creating a new user invitation.
 */
export interface UserCreationRequest {
  /** The email address of the user to be invited. */
  email: string;

  /** The role to be assigned to the user upon registration. */
  role: 'USER' | 'EDITOR' | 'ADMIN';

  /** An array of project IDs to pre-associate with the user upon registration. */
  projectIds: string[];
}

/**
 * Represents the request payload for completing the user registration
 */
export interface CompleteRegistrationRequest {
  /** The invited user name*/
  name: string;

  /** The invited user last name*/
  lastName: string;

  /** The invited user username*/
  username: string;

  /** The invited user password, it must be at least 8 characters*/
  password: string;
}

/**
 * Represents the API response for a user invitation.
 */
export interface InvitationResponse {
  /** The invited user's email. */
  email: string;

  /** The unique registration link generated by the server for the user to complete their signup. */
  registrationLink: string;

  /** The current status of the invitation. */
  status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
}

/**
 * Represents the public-facing information of a registered user.
 * This is used for API responses and should not contain sensitive data like passwords.
 */
export interface UserResponse {
  /** The unique numeric identifier for the user. */
  id: number;

  /** The user's unique username. */
  username: string;

  /** The user's first name. */
  name: string;

  /** The user's last name. */
  lastName: string;

  /** The user's email address. */
  email: string;

  /** The role assigned to the user, which determines their permissions. */
  role: 'USER' | 'EDITOR' | 'ADMIN';
}

/**
 * Represents the request payload for updating an existing user's information.
 */
export interface UpdateUserRequest {
  /** The user's updated username. */
  username: string;

  /** The user's updated first name. */
  name: string;

  /** The user's updated last name. */
  lastName: string;

  /** The user's updated email address. */
  email: string;

  /** The user's updated role. */
  userType: 'USER' | 'EDITOR' | 'ADMIN';
}

/**
 * Represents the basic information of a project.
 */
export interface Project {
  /** The unique numeric identifier for the project. */
  id: number;

  /** The name of the project. */
  name: string;

  /** A brief description of the project. */
  description: string;

  /** The timestamp when the project was created, in ISO format. */
  createdAt: string;
}

/**
 * Represents a request to start the password recovery process.
 *
 * This is typically sent when a user provides their email to receive
 * a password reset link.
 */
export interface PasswordRecoveryRequest {
  /** The email address associated with the user account. */
  email: string
}

/**
 * Represents a request to reset the user's password.
 *
 * This is sent after the user clicks the recovery link and provides
 * a new password.
 */
export interface PasswordResetRequest {
  /** The unique recovery token sent to the user's email. */
  token: string

  /** The new password to set for the user account. */
  password: string
}

/**
 * Represents a response returned by the password recovery endpoints.
 *
 * It provides feedback about the request status, along with optional
 * metadata or messages to display to the user.
 */
export interface PasswordRecoveryResponse {
  /** Optional email (useful for confirmation responses). */
  email?: string;

  /** A token to the recovery link. */
  token: string;

  /** Optional timestamp for when the action occurred. */
  timestamp?: string;

  /** Whether the operation was successful (e.g., link sent, password reset). */
  status: 'PENDING' | 'USED' | 'EXPIRED' | 'REVOKED';
}

/**
 * Represents a response returned by the password recovery validation endpoint
 *
 * It provides information about the validity of a request, along with its
 * associated details.
 * */
export interface TokenValidationResponse{
  valid: boolean;
  recovery: PasswordRecoveryRequest;
}
